Попробовал повторить шаги из статьи https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html

In [18]:
import numpy as np

In [19]:
b = np.array([[26.2, 103.5],
            [24.8, 127.0],
            [25.6, 126.0],
            [26.8, 124.8],
            [27.7, 124.7],
            [28.3, 121.6],
            [27.4, 149.7],
            [25.1, 188.8],
            [25.2, 193.6],
            [25.6, 173.9]])
b

array([[ 26.2, 103.5],
       [ 24.8, 127. ],
       [ 25.6, 126. ],
       [ 26.8, 124.8],
       [ 27.7, 124.7],
       [ 28.3, 121.6],
       [ 27.4, 149.7],
       [ 25.1, 188.8],
       [ 25.2, 193.6],
       [ 25.6, 173.9]])

In [20]:
mean_b = b.mean(axis = 0)
mean_b

array([ 26.27, 143.36])

In [21]:
deviation = np.subtract(b, mean_b)
deviation

array([[ -0.07, -39.86],
       [ -1.47, -16.36],
       [ -0.67, -17.36],
       [  0.53, -18.56],
       [  1.43, -18.66],
       [  2.03, -21.76],
       [  1.13,   6.34],
       [ -1.17,  45.44],
       [ -1.07,  50.24],
       [ -0.67,  30.54]])

In [22]:
deviation.T

array([[ -0.07,  -1.47,  -0.67,   0.53,   1.43,   2.03,   1.13,  -1.17,
         -1.07,  -0.67],
       [-39.86, -16.36, -17.36, -18.56, -18.66, -21.76,   6.34,  45.44,
         50.24,  30.54]])

Сделал цикл, чтобы проверить правильно ли я понимаю np.dot()

In [23]:
i = 0
result_cycle = 0
while i < len(deviation.T[0]):
    result_cycle += deviation.T[0, i] * deviation.T[1, i]
    print(f" {deviation.T[0, i]}, {deviation.T[1, i]}, произведение = {deviation.T[0, i] * deviation.T[1, i]} ")
    i +=1
    
result_cycle
        

 -0.07000000000000028, -39.859999999999985, произведение = 2.7902000000000102 
 -1.4699999999999989, -16.359999999999985, произведение = 24.04919999999996 
 -0.6699999999999982, -17.359999999999985, произведение = 11.631199999999959 
 0.5300000000000011, -18.559999999999988, произведение = -9.836800000000014 
 1.4299999999999997, -18.659999999999982, произведение = -26.68379999999997 
 2.030000000000001, -21.75999999999999, произведение = -44.17280000000001 
 1.129999999999999, 6.340000000000003, произведение = 7.1641999999999975 
 -1.1699999999999982, 45.440000000000026, произведение = -53.16479999999995 
 -1.0700000000000003, 50.24000000000001, произведение = -53.75680000000003 
 -0.6699999999999982, 30.54000000000002, произведение = -20.461799999999958 


-162.442

Видимо, в предыдущем результате где-то происходит округление.

In [24]:
result_np = np.dot(deviation.T[0], deviation.T[1])
result_np

-162.44199999999998

In [25]:
n = len(b)
n

10

In [26]:
f1_result_cycle = result_cycle / n
f1_result_cycle

-16.2442

In [27]:
f1_result_np = result_np / n
f1_result_np

-16.2442

Результат выше совпадает с тем, что дан в статье. Получается, что не вычитая 1, получаем ковариацию генеральной совокупности.

In [28]:
Cov = np.cov(b.T)[0, 1] # Ковариация выборочной совокупности

In [29]:
cov = ((n - 1)/n) * Cov # Ковариация генеральной совокупности

In [30]:
f1_result_np

-16.2442

In [31]:
cov

-16.244199999999996

In [32]:
Cov

-18.049111111111106