### Jupyter

Информация о команде

In [3]:
?print

OS shell

In [7]:
!cd

C:\Users\Aleksey\Jup\NumpyGuide


Магические команды

In [8]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%

%run, %load, %pycat, %%time, %%timeit

### Numpy

In [1]:
import numpy as np

In [11]:
a = [i for i in range(10)]

In [12]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
b = np.array(a)

In [14]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
type(b)

numpy.ndarray

In [16]:
b = np.array(a, dtype = float)

In [17]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
b = np.array([[i for i in range(10)], 
              [j for j in range(10,20)],
             [k for k in range(20, 30)]])

In [23]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [24]:
b.shape

(3, 10)

In [25]:
b.size

30

In [26]:
b[0][0]

0

In [27]:
b[0, 0]

0

In [28]:
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

View, ссылка

In [29]:
c = b[1:, 5:]

In [30]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

Отдельный объект

In [32]:
c = b[1:, 5:].copy()

In [33]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

### Линейная алгебра

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4])

In [3]:
a

array([0, 1, 2, 3, 4])

In [4]:
b = np.array([5, 6, 7, 8, 9])

In [5]:
b

array([5, 6, 7, 8, 9])

### Сложение векторов

Векторы складываются поэлементно

In [7]:
c = a + b
c

array([ 5,  7,  9, 11, 13])

In [8]:
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]

In [9]:
x3 = x1 + x2

In [10]:
x3

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
c = np.add(a, b)

In [12]:
c

array([ 5,  7,  9, 11, 13])

### Вычитание векторов

In [13]:
d = a - b

In [14]:
d

array([-5, -5, -5, -5, -5])

In [15]:
d = np.subtract(a, b)

In [16]:
d

array([-5, -5, -5, -5, -5])

In [17]:
a.shape == b.shape

True

### Умножение вектора на скаляр

In [18]:
a = np.array([5, 4, 8, 4, 3])

In [19]:
a

array([5, 4, 8, 4, 3])

In [20]:
c = a * 2

In [21]:
c

array([10,  8, 16,  8,  6])

In [22]:
c = -10 * a

In [23]:
c

array([-50, -40, -80, -40, -30])

In [24]:
c = 0.5 * a
c

array([2.5, 2. , 4. , 2. , 1.5])

In [25]:
2 * [1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [26]:
a

array([5, 4, 8, 4, 3])

In [27]:
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [28]:
np.dot(-10, a)

array([-50, -40, -80, -40, -30])

In [29]:
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

### Скалярное произведение векторов

In [30]:
a = np.array([1, 2, 3])

In [31]:
b = np.array([4, 5, 6])

In [32]:
a.shape, b.shape

((3,), (3,))

In [33]:
np.dot(a, b)

32

In [34]:
a[0] * b[0] + a[1] * b[1] + a[2] * b[2]

32

In [35]:
a @ b

32

### Операции с матрицами

In [38]:
A = np.array([[0, 1],
             [2, 3],
             [4, 5]])

In [39]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
B = np.array([[6, 7],
             [8, 9],
             [10, 11]])

In [41]:
B

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

### Сложение матриц

In [42]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [43]:
C = np.add(A, B)

In [44]:
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

### Вычитание матриц

In [45]:
D = A - B
D

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [46]:
D = np.subtract(A, B)

In [47]:
D

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

### Умножение матрицы на скаляр

In [48]:
X = np.array([[1, 2], [3, 4]])

In [49]:
X

array([[1, 2],
       [3, 4]])

In [50]:
Y = X * 3

In [51]:
Y

array([[ 3,  6],
       [ 9, 12]])

In [52]:
np.dot(X, 3)

array([[ 3,  6],
       [ 9, 12]])

### Умножение матриц

In [3]:
X1 = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [4]:
X1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
X2 = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

In [9]:
X2

array([[ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [10]:
X1.shape[1] == X2.shape[0]

True

In [11]:
Z = np.dot(X1, X2)

In [12]:
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [13]:
Z.shape

(3, 4)

In [14]:
Z[0, 0]

29

In [15]:
X1[0, 0] * X2[0, 0] + X1[0, 1] * X2[1, 0]

29

In [16]:
Z[0, 1]

32

In [17]:
X1[0, 0] * X2[0, 1] + X1[0, 1] * X2 [1, 1]

32

### Numpy.linalg

Возведение матрицы в квадрат

In [18]:
A = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

In [19]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
A_square = np.dot(A, A)

In [21]:
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [23]:
A_square = np.linalg.matrix_power(A, 2)

In [24]:
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

Создание единичной матрицы

In [25]:
I = np.eye(3)

In [26]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Умножение матрицы на единичную матрицу

In [27]:
A = np.array([[1, 2],
             [3, 4],
             [5, 6]])

In [28]:
I = np.eye(2)

In [29]:
np.dot(A, I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [30]:
I = np.eye(3)

In [31]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Транспонирование матрицы

In [32]:
A = np.array([[11, 13],
             [16, 9],
             [8, 15]])

In [36]:
At = A.transpose()
At

array([[11, 16,  8],
       [13,  9, 15]])

In [39]:
At = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

In [40]:
X = np.array([[1, 2],
             [3, 4],
             [5, 6]])

In [41]:
Y = np.array([[0, 1],
             [3, 4],
             [6, 7],
             [2, 5]])

In [42]:
Yt = Y.T

In [43]:
np.dot(X, Y.T)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

Определитель и ранг матрицы

In [44]:
A = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

In [45]:
np.linalg.det(A)

0.0

In [46]:
np.linalg.matrix_rank(A)

2

In [47]:
B = np.array([[7, 4, 5],
             [8, 3, 2],
             [6, 10, 12]])

In [48]:
np.linalg.det(B)

85.99999999999997

In [49]:
np.linalg.matrix_rank(A)

2

In [50]:
C = np.array([[1, 2],
             [3, 4],
             [5, 6]])

In [52]:
np.linalg.matrix_rank(C)

2

Вычисление обратной матрицы

In [53]:
B = np.array([[7, 4, 5],
             [8, 3, 2],
             [6, 10, 12]])

In [54]:
B_inv = np.linalg.inv(B)

In [55]:
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

### Автоматическое создание массивов

In [6]:
a = np.zeros((3, 4))

In [4]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b = np.ones((5, 3))

In [8]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [16]:
np.linspace(0, 10, 100) # включая правую границу
#   начало, конец, количество чисел

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [20]:
np.logspace(2, 5, 4) # степени числа 10

array([   100.,   1000.,  10000., 100000.])

### Генерация случайных чисел

In [22]:
np.random.sample() # [0.0, 1.0)

0.7560836182526727

In [23]:
np.random.sample(3)


array([0.40867622, 0.1975615 , 0.57474332])

In [24]:
np.random.sample((2, 3))

array([[0.27144885, 0.49175858, 0.08577912],
       [0.8582506 , 0.140365  , 0.32530497]])

In [25]:
np.random.sample((3, 3, 3))

array([[[0.88066581, 0.70256208, 0.56223432],
        [0.40727226, 0.22469247, 0.96478301],
        [0.90188105, 0.92071468, 0.13976511]],

       [[0.82081981, 0.82465818, 0.509466  ],
        [0.51802181, 0.06173307, 0.09857193],
        [0.32294395, 0.87658301, 0.41260065]],

       [[0.31522954, 0.54194878, 0.40928518],
        [0.69378116, 0.64712114, 0.42996376],
        [0.17499107, 0.66654618, 0.85612996]]])

In [28]:
np.random.randn() # с нормальным распределением
# среднее значение = 0, среднеквадратичное отклонение = 1

-0.28667902029174847

In [29]:
np.random.randn(10)

array([ 0.20273345, -0.85035283, -0.38115136,  1.4717763 ,  0.3593447 ,
       -0.91497121,  0.20085638, -1.00894743, -1.5017197 ,  1.01057135])

In [32]:
np.random.randn(3, 4) # одна пара скобок

array([[ 0.59276488,  1.10881924, -0.287035  ,  0.11794383],
       [ 0.38331689, -0.40150101,  0.75325121,  1.44433404],
       [-0.68815444,  0.78036415, -0.46247324,  0.69830475]])

In [33]:
np.random.randint(0, 100, 10) # интервал, не включая правую границу и количество чисел

array([21, 28, 55, 21, 34, 21, 32, 22, 76, 51])

In [34]:
np.random.randint(0, 10, (3, 4))

array([[8, 8, 1, 3],
       [5, 9, 7, 4],
       [5, 7, 2, 3]])

In [35]:
b = np.array([5, 1, 3, 6, 2, 76])

In [38]:
np.random.choice(b, 3)

array([6, 1, 2])

In [47]:
np.random.seed(53534) # далее результаты в одинаковой последовательности

In [48]:
np.random.randint(0, 10, 3)

array([5, 3, 4])

In [49]:
np.random.randint(0, 10, 3)

array([4, 0, 5])

In [50]:
np.random.randint(0, 10, 3)

array([3, 6, 9])

In [51]:
np.random.randint(0, 10, 3)

array([3, 9, 8])

### Изменение формы массива

In [52]:
a = np.arange(12)

In [53]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
# Вместо неизвестного параметра можно поставить -1
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
np.reshape(a, (-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
# in place
a.resize(3, 4)

In [62]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Соединение массивов

In [67]:
a = np.zeros((2, 3))

In [68]:
b = np.ones((2, 3))

In [70]:
v = np.vstack((a, b))

In [71]:
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.concatenate((a, b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
np.concatenate((a, b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [74]:
h = np.hstack((a, b))

In [75]:
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

Соединение в глубину

In [76]:
d = np.dstack([a, b])

In [77]:
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

### Выбор данных

In [78]:
a = np.random.randint(0, 20, 10)

In [79]:
a

array([ 9,  9,  2,  1, 17, 18, 14, 14,  0, 12])

In [80]:
a[a > 10]

array([17, 18, 14, 14, 12])

In [81]:
a[(a > 10) & (a % 2 == 0)]

array([18, 14, 14, 12])

In [82]:
a[(a > 10) | (a % 3 == 0)]

array([ 9,  9, 17, 18, 14, 14,  0, 12])

In [84]:
np.where(a > 10) # получаем не сами числа, а их индексы!

(array([4, 5, 6, 7, 9], dtype=int64),)

In [85]:
a = [1, 4, 7]
b = [9, 2, 5]

In [86]:
np.where([True, False, True], a, b) # в [] маска

array([1, 2, 7])

In [87]:
np.where([False, False, True], a, b)

array([9, 2, 7])

In [88]:
np.where([True, False, False], a, b)

array([1, 2, 5])

In [89]:
np.where([False, False, False], a, b)

array([9, 2, 5])

In [90]:
np.where([True, True, True], a, b)

array([1, 4, 7])

### Сортировка

In [91]:
a = np.array([[1, 3, 9, 9],
             [5, 0, 1, 5],
             [2, 7, 3, 5]])

In [92]:
a

array([[1, 3, 9, 9],
       [5, 0, 1, 5],
       [2, 7, 3, 5]])

In [93]:
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [94]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [96]:
a[:, 0].argsort(axis = 0)

array([0, 2, 1], dtype=int64)

In [97]:
a[a[:, 0].argsort(axis = 0)]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

### Случайное перемешивание массивов

In [98]:
a = np.arange(10)

In [99]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
# in place
np.random.shuffle(a)

In [101]:
a

array([7, 6, 5, 4, 0, 9, 1, 3, 2, 8])

In [103]:
a = np.arange(12).reshape(4, 3)

In [104]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Математические действия с массивами

In [105]:
a = np.arange(1, 7).reshape(2, 3)

In [106]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
# Логарифм по основанию e
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [108]:
# Экспонента
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [109]:
a.sum()

21

In [110]:
a.sum(axis = 0)

array([5, 7, 9])

In [111]:
a.sum(axis = 1)

array([ 6, 15])

In [112]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

In [113]:
a

array([[1, 2, 3],
       [4, 5, 6]])

Поэлементное умножение матриц

In [114]:
a = np.arange(12).reshape(3, -1)

In [115]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
b = np.arange(12, 24).reshape(3, -1)

In [117]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [118]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Broadcasting

In [120]:
a = np.array([[2, 5],
             [3, 4],
             [6, 1]])

In [121]:
a

array([[2, 5],
       [3, 4],
       [6, 1]])

In [122]:
b = np.array([1, 2])

In [124]:
a + b # к каждой строке a прибавляется b

array([[3, 7],
       [4, 6],
       [7, 3]])

In [125]:
c = np.array([[1],
             [2],
             [3]])

In [126]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

### Статистические функции

In [127]:
a = np.random.randint(0, 12, (3, 4))

In [128]:
a

array([[ 7,  7,  3,  7],
       [ 1, 11,  3,  0],
       [ 1,  8,  2,  4]])

In [129]:
a.min()

0

In [132]:
a.min(axis = 0) # для каждого столбца

array([1, 7, 2, 0])

In [133]:
a.min(axis = 1) # для каждой строки

array([3, 0, 1])

In [134]:
a.mean(axis = 1) 

array([6.  , 3.75, 3.75])

In [135]:
# Среднеквадратичное отклонение
a.std()

3.278719262151

### Запись и чтение из массива

np.save('a.npy', a)

b = np.load('a.npy')